const videos = document.querySelector('#videos');
for(let i=1;i<=5;i++){const n=String(i).padStart(2,'0');const card=document.createElement('article');card.className='video-card';card.innerHTML=`<video controls playsinline preload="none" poster="assets/poster-${n}.jpg" aria-label="Video sample ${n}"><source src="assets/video-${n}.mp4" type="video/mp4">Your browser does not support this video. <a href="assets/video-${n}.mp4">Download video</a></video><div class="card-caption">Video sample ${n}<span>VIDEO / ${n}</span></div>`;videos.append(card);}
document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause()})));
const gallery=document.querySelector('#gallery'),dialog=document.querySelector('#lightbox');
function render(filter){gallery.replaceChildren();work.filter(w=>filter==='All'||w.category===filter).forEach(w=>{const card=document.createElement('figure');card.className='art';const b=document.createElement('button');b.setAttribute('aria-label',`View ${w.title}`);const img=document.createElement('img');img.src=w.src;img.alt=w.title;img.loading='lazy';b.append(img);b.addEventListener('click',()=>{document.querySelector('#large-image').src=w.src;document.querySelector('#large-image').alt=w.title;document.querySelector('#image-caption').textContent=w.title;dialog.showModal()});const caption=document.createElement('figcaption');caption.textContent=w.title;const cat=document.createElement('span');cat.textContent=w.category;caption.append(cat);card.append(b,caption);card.style.setProperty("--order",gallery.childElementCount);gallery.append(card)});gallery.classList.remove("gallery-changing");void gallery.offsetWidth;gallery.classList.add("gallery-changing")}
render('All');document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render(b.dataset.filter)}));document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});

const motionOK=matchMedia('(prefers-reduced-motion: no-preference)').matches;
if(motionOK && matchMedia('(hover:hover)').matches){
const scene=document.querySelector('.scene'),stage=document.querySelector('.scene-stage');
scene.addEventListener('pointermove',e=>{if(document.body.classList.contains('motion-paused'))return;const r=scene.getBoundingClientRect();stage.style.setProperty('--ry',`${((e.clientX-r.left)/r.width-.5)*18}deg`);stage.style.setProperty('--rx',`${-((e.clientY-r.top)/r.height-.5)*12}deg`)});
scene.addEventListener('pointerleave',()=>{stage.style.setProperty('--ry','-8deg');stage.style.setProperty('--rx','0deg')});
document.addEventListener('pointermove',e=>{const card=e.target.closest('.art,.video-card');if(!card || document.body.classList.contains("motion-paused"))return;const r=card.getBoundingClientRect();card.style.setProperty('--ty',`${((e.clientX-r.left)/r.width-.5)*6}deg`);card.style.setProperty('--tx',`${-((e.clientY-r.top)/r.height-.5)*6}deg`)});
document.addEventListener('pointerout',e=>{const card=e.target.closest('.art,.video-card');if(card&&!card.contains(e.relatedTarget)){card.style.setProperty('--tx','0deg');card.style.setProperty('--ty','0deg')}});
}
if(motionOK && 'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section-heading,.about-grid,.skill-grid,.project-list article').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)})}

document.querySelectorAll('.hero h1 em span').forEach((el,i)=>el.style.setProperty('--letter',i));
const toggle=document.querySelector('#motion-toggle');let paused=!motionOK;
function setMotion(){document.body.classList.toggle('motion-paused',paused);toggle.setAttribute('aria-pressed',String(paused));toggle.textContent=paused?'Enable animations':'Pause animations'}
setMotion();toggle.addEventListener('click',()=>{paused=!paused;setMotion()});
let scrollQueued=false;function updateProgress(){const height=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--progress',height>0?scrollY/height:0);scrollQueued=false}addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(updateProgress)}},{passive:true});updateProgress();
if(motionOK && 'IntersectionObserver' in window){const stagger=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');stagger.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.video-card,.skill-grid article,.tools').forEach((el,i)=>{el.classList.add('reveal-ready');el.style.transitionDelay=`${i%4*75}ms`;stagger.observe(el)})}
